### ISSUE TITLE
'Adafruit_USBD_HID' does not name a type

### ISSUE THREAD

**Issue by charlesfayal** [Seeed-Studio/Seeed_Arduino_DAPLink#11]
**Describe the bug**

**To Reproduce**
Follow this guide.
https://wiki.seeedstudio.com/Arduino-DAPLink/#2-installing-the-adafruit_tinyusb_arduino-library

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac M1

**Additional context**

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
