### ISSUE TITLE
Can't compile: [error: 'USBDevice' was not declared in this scope]

### ISSUE THREAD

**Issue by tglaria** [Seeed-Studio/Seeed_Arduino_DAPLink#14]
I'm getting an error during compilation.

*:\***\simple_daplink\src\DAP.cpp:108:16: error: 'USBDevice' was not declared in this scope
       length = USBDevice.getSerialDescriptor((uint16_t*) info);

**To Reproduce**
[after installation]
1. Load simple_daplink example.
2. Verify
3. See error

**Expected behavior**
I would expect the compilation to succed without error.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE: Arduino IDE, 2.3.3

**Additional context**
I'm trying to use some SAMD21 custom boards as CMSIS-DAP debugger, for this I need to change the pins available.
I've tried using Adafruit_TinyUSB Library v3.4.1, v2.0.0 and v1.0.0. It won't compile on neither.

Is this library still working / mantained?

**Comment by Lesords** [comment]
@LynnL4 Help with this one.

**Comment by tglaria** [comment]
I first asked on the arduino forum and got a solution (after I asked here).
What I had to do to manage to compile, was to include the TinyUSB library in the DAP.cpp code:
```
#include "DAP_config.h"
#include "DAP.h"
#include <Adafruit_TinyUSB.h>  // <---- Add this 
```

Though I haven't tested it yet.

**Comment by LynnL4** [comment]
Hi，Please try this fix, thanks!
https://github.com/Seeed-Studio/Seeed_Arduino_DAPLink/commit/24595ccae138155c0be729c9060cb32aca28e73f

**Comment by Lesords** [comment]
> Hi，Please try this fix, thanks! [24595cc](https://github.com/Seeed-Studio/Seeed_Arduino_DAPLink/commit/24595ccae138155c0be729c9060cb32aca28e73f)

@tglaria 

Hello，does this solve your problem?

If so, I will close this issue

**Comment by tglaria** [comment]
@Lesords 
Just checked, and it did compile.
So I guess the issue is resolved.

Thank you.

**Comment by Lesords** [comment]
OK, I'm going to close this issue. If you have other questions, you are welcome to reopen it.
