### ISSUE TITLE
arduino ide编译报错

### ISSUE THREAD

**Issue by aktoey** [Seeed-Studio/Seeed_Arduino_DAPLink#9]
在arduino ide1.8.15上面安装好最新的seeed开发板库，然后添加tinyusb库和这个库，然后按照seeed里面如何制作daplink的文章配置IDE结果编译完成后报错，如下：

simple_daplink:58:19: error: cannot declare variable 'usb_hid' to be of abstract type 'Adafruit_USBD_HID'
 Adafruit_USBD_HID usb_hid;
                   ^~~~~~~
In file included from C:\Users\cheng\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master\src/Adafruit_TinyUSB.h:40:0,
                 from C:\Users\cheng\AppData\Local\Temp\arduino_modified_sketch_479677\simple_daplink.ino:46:
C:\Users\cheng\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master\src/arduino/hid/Adafruit_USBD_HID.h:30:7: note:   because the following virtual functions are pure within 'Adafruit_USBD_HID':
 class Adafruit_USBD_HID : public Adafruit_USBD_Interface {
       ^~~~~~~~~~~~~~~~~
In file included from C:\Users\cheng\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.1\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/Adafruit_TinyUSB_Core.h:35:0,
                 from C:\Users\cheng\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.1\cores\arduino/Arduino.h:171,
                 from C:\Users\cheng\AppData\Local\Temp\arduino_build_309041\sketch\simple_daplink.ino.cpp:1:
C:\Users\cheng\AppData\Local\Arduino15\packages\Seeeduino\hardware\samd\1.8.1\cores\arduino/TinyUSB/Adafruit_TinyUSB_ArduinoCore/Adafruit_USBD_Device.h:38:22: note: 	virtual uint16_t Adafruit_USBD_Interface::getDescriptor(uint8_t, uint8_t*, uint16_t)
     virtual uint16_t getDescriptor(uint8_t itfnum, uint8_t* buf, uint16_t bufsize) = 0;
                      ^~~~~~~~~~~~~
使用 1.0.3  版本的库 Adafruit_TinyUSB_Arduino-master 在文件夹： C:\Users\cheng\Documents\Arduino\libraries\Adafruit_TinyUSB_Arduino-master 
使用 1.0.2  版本的库 Seeed_Arduino_DAPLink-master 在文件夹： C:\Users\cheng\Documents\Arduino\libraries\Seeed_Arduino_DAPLink-master 
exit status 1
cannot declare variable 'usb_hid' to be of abstract type 'Adafruit_USBD_HID'

请帮忙看下这个是什么原因造成的，谢谢啦。

**Comment by Pillar1989** [comment]
请不要重复提问
